### PR TITLE
safe area for iPhone XS, iPhone XR and iPhone XS MAX

### PR DESCRIPTION
**Pull request by pengfeizhao-gh**
The Pixels (DPI)  of iPhoneX are the same as iPhoneXS, iPhoneXR are the same as iPhoneXS Max

### CODE REVIEW

**Comment by brentvatne** [comment]
thank you!

**Comment by hagaigold** [comment]
isn't the isIPhoneX_deprecated check will return false before this fix for RN version >= 0.50.0 ?
there is a commit to "fix" the isIPhoneX_deprecated, but it probably will be just in the next RN release.

https://github.com/react-community/react-native-safe-area-view/blob/3cbc8d2a79795f04a5b1a2d020a992466552a7ac/index.js#L31-L42

**Comment by brentvatne** [comment]
great point @hagaigold - I will remove that line

**Comment by brentvatne** [comment]
done

**Pull request merged**
