### PR TITLE
Function to use for components styling

### PR DESCRIPTION
**Pull request by gabgagnon**
I found it usefull for absolute positioned components, using it able us to not block others components under it.
Not sure if the signature is perfect, change it if you which.

### CODE REVIEW

**Comment by Elijen** [comment]
Why not just keep the name getInset?

**Comment by Arjanvanmaren** [comment]
Could this be merged in please?

**Comment by gabgagnon** [comment]
@brentvatne Can you re-release the library? You merged the branch few minutes after you changed the version of the library so it didn't update on npm.

thanks you!

**Comment by brentvatne** [comment]
done! thanks

**Comment by brentvatne** [comment]
0.14.0

**Pull request merged**
