### PR TITLE
fix #21: Add support for Android

### LINKED ISSUE #21: Add support for Android?
When i set my status bar in android app gets rendered under the status bar.
Also now a days we are getting android phones with notches and all that.

So does it make sense to add support for android?
it could be the matter of just returning `StatusBar.currentHeight` instead of `0`

Does it sound like a good idea?

### PR DESCRIPTION
**Pull request by xiaweiss**
change log: 
改动：
1. In project without Expo, global.Expo value is undefined. So add a condition, get statusBarHeight with react-native StatusBar.currentHeight
在没有使用 Expo 的项目中，global.Expo 值为 undefined。所以添加一个条件，使用 react-native 提供的 StatusBar.currentHeight 来获取状态栏高度

2. winY of measureInWindow callback，it's value is based status bar bottom, different with iOS.  so the real winY of screen need plus statusBarHeight
安卓通过 measureInWindow 获取到的回调参数 winY，它的值与 iOS 的不同，是基于状态栏的底部的。所以要加上状态栏高度，才能得到相对于窗口，真正的 winY 值。

3. In Android, onLayout of View events （not _onLayout）, measureInWindow can not get winWidth and winHeight, them value is 0. So need to do _layout function again in componentDidMount, and must use setImmediate global function.
在安卓里，View 的 onLayout（不是 _onLayout）里执行的 measureInWindow，获取不到 winWidth 和 winHeight，它们的值都是 0。所以需要在组件挂载，并且延迟后，再执行一次 _onLayout

4. In callback of measureInWindow functions , use Dimensions.get('screen') to get height and width again，instead of iPhoneX height and width
在 measureInWindow 的回调函数里，使用 Dimensions.get('screen') 再次获取宽高，而不是使用 iPhoneX 的设备宽高

### CODE REVIEW

**Comment by onitzschke** [comment]
@brentvatne we need a patch that fixed the issue on android devices with notch. What's about this PR?

**Comment by brentvatne** [comment]
I don't think that this PR is related. There is no native API exposed to React Native currently for getting this information - we need https://github.com/facebook/react-native/pull/20999

**Comment by onitzschke** [comment]
@brentvatne here is an issue that explain my issue: https://github.com/facebook/react-native/issues/23693

**Comment by brentvatne** [comment]
this isn't needed anymore on 1.0 of this library 👼 see readme for more info :) thanks though!

**Pull request closed without merging**
