### PR TITLE
Exposes API to fix absolute positioned items

### PR DESCRIPTION
**Pull request by sidferreira**

### CODE REVIEW

**Comment by hkung77** [comment]
Is it also possible to export the bottom footer height?

**Comment by sidferreira** [comment]
@hkung77 I think so

**Comment by ifours** [comment]
Same here. I had to copy `statusBarHeight` function to my project, because some screen depends on top insert. But in my opinion its better to use the `static` method on SafeView to export that functions. What do you think @sidferreira ?

**Comment by sidferreira** [comment]
@ifours it makes sense... But in the end I found another solution to my issue.

**Comment by brentvatne** [comment]
https://github.com/facebook/react-native/pull/20999 will properly expose safe area insets across iOS and Android, the current API used internally is going to change over to it soon, so we won't add this here. Thanks!

**Pull request closed without merging**
