### PR TITLE
Use peerDependencies for react and react-native

### PR DESCRIPTION
**Pull request by messense**
Fix possible error on startup:

```
Failed to load bundle(http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false) with error:(Ambiguous resolution: module '/Users/messense/workspace/bosondata/brm-apps/index.ios.js' tries to require 'react-native', but there are several files providing this module. You can delete or fix them: 

/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native-safe-area-view/node_modules/react-native/package.json

/Users/messense/workspace/bosondata/brm-apps/node_modules/react-native/package.json
```

### CODE REVIEW

**Comment by paulsoh** [comment]
I need this! thx

**Comment by suark** [comment]
I also need this. Not sure how it works without this.

**Comment by deadcoder0904** [comment]
Any updates ❓

**Comment by lizhuoyuan** [comment]
Hey,I did this:
npm install react-native-safe-area-view 
and 
   "dependencies": {
 -    "hoist-non-react-statics": "^2.3.1",
 -    "react": "16.0.0-alpha.12",
 -    "react-native": "^0.48.4"
 +    "hoist-non-react-statics": "^2.3.1"
 +  },
 +  "peerDependencies": {
 +    "react": "16.0.0",
 +    "react-native": "^0.50.1"
    }

it doesn't work 
what should I do?

**Comment by davepack** [comment]
Thank you for this! Sorry for the delay!

**Pull request merged**
