### PR TITLE
New iphone X

### PR DESCRIPTION
**Pull request by NarendraPunchh**

### CODE REVIEW

**Comment by NarendraPunchh** [comment]
Update safe area for iPhone XS and iPhone XS MAX

**Comment by brentvatne** [comment]
won't this also match iphone 7/8 plus?

**Comment by brentvatne** [comment]
resolved in https://github.com/react-community/react-native-safe-area-view/pull/44, nonetheless thank you for the PR!

**Comment by NarendraPunchh** [comment]
Thanks for the reverting back @brentvatne, but iPhone 7/8 Plus are **414 X 736** resolutions which is less then **812** and **896**. But still the other commit was better.
:-)

**Pull request closed without merging**
